// GENERATED by scripts/dump_brain_film_data.py - do not edit.
// Real per-unit world-signal from the saved heldout pools.
window.BRAIN_DATA = {
 "source": "fullruns/l3_h8_heldout/states d0.45 seed 8 (saved pools; H2 integrity-gate reference dumps)",
 "published_mean": 0.752,
 "seed": 8,
 "seed_pooled_target": 0.7594,
 "hidden": 96,
 "display_units": [
  6,
  11,
  14,
  23,
  42,
  43,
  56,
  57,
  58,
  71,
  93,
  94
 ],
 "unit_activity": [
  0.5117,
  1.0,
  0.7246,
  0.9574,
  0.8132,
  0.8541,
  0.8566,
  0.9933,
  0.9363,
  0.8568,
  0.9268,
  0.9348
 ],
 "unit_auroc": [
  0.4374,
  0.5836,
  0.4274,
  0.5472,
  0.4177,
  0.455,
  0.419,
  0.5424,
  0.5531,
  0.542,
  0.4414,
  0.4252
 ],
 "unit_signal": [
  0.7489,
  1.0,
  0.8687,
  0.5642,
  0.9845,
  0.5381,
  0.9686,
  0.5076,
  0.6347,
  0.5023,
  0.7009,
  0.8949
 ],
 "untrained_unit_auroc": [
  0.4726,
  0.4899,
  0.4548,
  0.498,
  0.4572,
  0.4695,
  0.4676,
  0.5237,
  0.4997,
  0.4967,
  0.4915,
  0.4545
 ],
 "ring_units": [
  11,
  42,
  56,
  94,
  14,
  6
 ],
 "obs_masking": {
  "none": 0.7525,
  "vision_masked": 0.6862,
  "intero_masked": 0.756,
  "all_masked": 0.5
 }
};
