/* ItaSoRL "Two Minds" brain film - deterministic canvas renderer.
 *
 * A stylized (illustrative, not data-literal) recreation of the brain-pair
 * story: the same mind living in a REAL and a FAKE world, with teal rings
 * blooming on the memory cells that hold the clue.
 *
 * Design contract (matches viz/player capture pipeline):
 *   window.__ready    true once fonts are loaded and first frame drew
 *   window.__size     [w, h] canvas pixel box
 *   window.__duration total ms
 *   window.__seek(t)  render the exact frame at time t (pure function of t)
 *   window.__sceneSource = "stylized"  (this film is illustrative art)
 *
 * Numbers are REAL - the canonical L3 headline result (docs/FINDINGS.md TL;DR,
 * n = 10 seeds, read out never rewarded):
 *   untrained mind        0.488  (chance floor)
 *   pre-registered bar    0.65   ("past this line = it can tell")
 *   survival-trained mind 0.752  (90% CI [0.698, 0.807])
 *   outside watcher gate  0.928
 *   vision masked         0.686 / all senses masked 0.500 (FINDINGS 14.6, A2)
 * The layout/motion remain stylized; the numbers are not. Since the labeled
 * pass, the dots are grounded too: sense/action/readout names mirror the real
 * obs and head spec (viz_mind_learning.py SENSOR_GROUPS / MOTOR_HEADS), the
 * memory spine shows 12 real GRU units of the representative brain, and the
 * teal rings sit on the units with the highest MEASURED world-signal
 * (brain-data.js, generated by scripts/dump_brain_film_data.py from the saved
 * heldout pools).
 *
 * Seamless loop: every animated quantity is periodic in T = duration.
 * Comet periods divide T; breathing/drift use integer cycles per loop; the
 * training sweep and ring envelopes are functions of (t mod T). Frame(0)
 * therefore equals Frame(T) exactly - no crossfade seam needed.
 */

"use strict";

// ---------------------------------------------------------------- params
const Q = new URLSearchParams(location.search);
const SEC = Q.get("sec") || "memory";
const LAYOUT = Q.get("layout") || "wide"; // wide 1920x1080 | vertical 1080x1920
const W = LAYOUT === "vertical" ? 1080 : 1920;
const H = LAYOUT === "vertical" ? 1920 : 1080;
const T = 12000; // ms per loop

// ---------------------------------------------------------------- palette
const BG0 = "#0a0910";
const BG1 = "#131022";
const INK = "#ece9f5";
const MUTED = "#78728f";
const TEAL = [53, 181, 162];
const AMBER = [232, 184, 75];
const REAL_C = [124, 156, 232]; // blue-lavender
const FAKE_C = [169, 139, 224]; // violet
const CORAL = [235, 108, 92];   // the flaw: sloppy physics in the fake world

// Per-section presentation: caption headline, narration script, and which
// node groups stay at full brightness (null = no dimming). The ring/verdict
// timeline is shared across sections; each section retells it from its own
// vantage point.
const SECTIONS = {
  overview: {
    headline: "Same brain, two worlds, one flaw.",
    focus: null,
    narration: [
      { u0: 0.00, u1: 0.10, text: "the same brain lives in both worlds" },
      { u0: 0.10, u1: 0.26, text: "the fake's physics are subtly wrong: an outside watcher spots it 93% of the time" },
      { u0: 0.26, u1: 0.42, text: "survival training teaches memory to catch the mismatch" },
      { u0: 0.42, u1: 0.86, text: "same brain, two verdicts: 75%, past the 0.65 bar, where 50% is a coin flip" },
      { u0: 0.86, u1: 1.00, text: "read out, never rewarded: without pressure, the clue fades" },
    ],
  },
  senses: {
    headline: "It all starts at the senses.",
    focus: ["sense"],
    // 10 labeled sensor groups make a taller arc than the old anonymous 8;
    // a gentler zoom keeps "see front" and "ground + light" inside the panel.
    zoom: 1.25,
    narration: [
      { u0: 0.00, u1: 0.10, text: "every world reaches the brain only through its senses" },
      { u0: 0.10, u1: 0.26, text: "the fake's physics are subtly wrong: an outside watcher spots it 93% of the time" },
      { u0: 0.26, u1: 0.42, text: "cover its eyes and detection drops to 69%; cover every sense and it falls to 50%" },
      { u0: 0.42, u1: 0.86, text: "downstream, memory turns the mismatch into a verdict: 75%" },
      { u0: 0.86, u1: 1.00, text: "read out, never rewarded: without pressure, the clue fades" },
    ],
  },
  process: {
    headline: "Signals mix until patterns form.",
    focus: ["process"],
    zoom: 1.45,
    narration: [
      { u0: 0.00, u1: 0.10, text: "process cells mix every sense into patterns" },
      { u0: 0.10, u1: 0.26, text: "the fake's flaw is faint: one wrong channel among many" },
      { u0: 0.26, u1: 0.42, text: "survival training routes the mismatch toward memory" },
      { u0: 0.42, u1: 0.86, text: "same brain, two verdicts: 75%, past the 0.65 bar" },
      { u0: 0.86, u1: 1.00, text: "read out, never rewarded: without pressure, the clue fades" },
    ],
  },
  memory: {
    // The approved hero: no dimming - the rings already carry the emphasis.
    headline: "Teal rings = the cells that hold the clue.",
    focus: null,
    narration: [
      { u0: 0.00, u1: 0.10, text: "the same brain lives in both worlds" },
      { u0: 0.10, u1: 0.26, text: "the fake's physics are subtly wrong: an outside watcher spots it 93% of the time" },
      { u0: 0.26, u1: 0.42, text: "survival training teaches memory to catch the mismatch" },
      { u0: 0.42, u1: 0.86, text: "same brain, two verdicts: 75%, past the 0.65 bar, where 50% is a coin flip" },
      { u0: 0.86, u1: 1.00, text: "read out, never rewarded: without pressure, the clue fades" },
    ],
  },
  actions: {
    headline: "Actions and guesses: the brain's bets.",
    focus: ["action", "guess"],
    zoom: 1.45,
    narration: [
      { u0: 0.00, u1: 0.10, text: "actions and guesses are the brain's bets about its world" },
      { u0: 0.10, u1: 0.26, text: "sloppy physics makes the fake world's bets subtly miss" },
      { u0: 0.26, u1: 0.42, text: "each miss is a lesson: memory catches the mismatch" },
      { u0: 0.42, u1: 0.86, text: "same brain, two verdicts: 75%, where 50% is a coin flip" },
      { u0: 0.86, u1: 1.00, text: "read out, never rewarded: without pressure, the clue fades" },
    ],
  },
};
const SECTION = SECTIONS[SEC] || SECTIONS.memory;

// Focus dimming: non-focus groups drop to a clearly supporting role.
function kindEmphasis(kind) {
  if (!SECTION.focus) return 1;
  return SECTION.focus.includes(kind) ? 1 : 0.25;
}

// Per-section camera: magnification applied to node geometry (not the canvas
// transform), so UI chrome stays crisp while the focused group is centered
// and enlarged in its panel.
const FOCUS_Z = SECTION.focus && SECTION.zoom ? SECTION.zoom : 1;

// Text shadow helpers: dark halo lifts type off the glow field.
function textShadowOn() {
  ctx.shadowColor = "rgba(0,0,0,0.85)";
  ctx.shadowBlur = 8;
  ctx.shadowOffsetY = 1;
}
function textShadowOff() {
  ctx.shadowColor = "transparent";
  ctx.shadowBlur = 0;
  ctx.shadowOffsetY = 0;
}

const rgba = (c, a) => `rgba(${c[0]},${c[1]},${c[2]},${a})`;
const lerp = (a, b, p) => a + (b - a) * p;
const clamp01 = (x) => Math.max(0, Math.min(1, x));
const smooth = (p) => { p = clamp01(p); return p * p * (3 - 2 * p); };
const frac = (x) => x - Math.floor(x);
const TAU = Math.PI * 2;

function mulberry32(seed) {
  let s = seed >>> 0;
  return function () {
    s |= 0; s = (s + 0x6D2B79F5) | 0;
    let z = Math.imul(s ^ (s >>> 15), 1 | s);
    z = (z + Math.imul(z ^ (z >>> 7), 61 | z)) ^ z;
    return ((z ^ (z >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------- real data
// Measured brain data from the saved heldout pools (the H2 integrity-gate
// reference dumps), extracted by scripts/dump_brain_film_data.py. Labels and
// ring placement are real; positions and motion stay stylized.
const DATA = window.BRAIN_DATA;
if (!DATA) throw new Error("brain-data.js missing: run scripts/dump_brain_film_data.py");

// Real label vocabulary, mirroring the original brain-graph viz
// (artifacts/clip_audit/viz_src/viz_mind_learning.py SENSOR_GROUPS / MOTOR_HEADS).
const SENSE_LABELS = [
  "see front", "see right", "see back", "see left", "smell",
  "speed", "direction", "hunger + thirst", "body state", "ground + light",
];
const GLITCH_SENSE = 5; // "speed": the seam is the velocity law
const ENC_LABELS = ["enc-0", "enc-12", "enc-25", "enc-37", "enc-50", "enc-63"]; // 6 of 64
const ACTION_LABELS = ["move", "turn", "eat", "drink", "scent"];
const GUESS_LABELS = ["outlook", "expects to see", "expects to feel"];

// ---------------------------------------------------------------- layout
// One "mind" = a constellation: senses arc -> process cloud -> MEMORY spine
// (the hero) -> actions/guesses. Positions are in a local 0..1 box, mirrored
// for the FAKE side so the two minds face each other like a Rorschach.

function buildMind(seed) {
  const R = mulberry32(seed);
  const nodes = [];   // {x,y,r,kind,label,phase,freqK}
  const edges = [];   // {a,b,w,comet:{P,phi}|null}
  const add = (x, y, r, kind, label) => {
    nodes.push({
      x, y, r, kind, label,
      phase: R() * TAU,
      freqK: 2 + Math.floor(R() * 3), // 2..4 integer cycles per loop
    });
    return nodes.length - 1;
  };

  // Senses: the 10 real sensor groups, gentle arc on the far side.
  const senses = [];
  for (let i = 0; i < SENSE_LABELS.length; i++) {
    const p = i / (SENSE_LABELS.length - 1);
    const y = lerp(0.14, 0.86, p);
    const x = 0.055 + 0.05 * Math.sin(p * Math.PI) + (R() - 0.5) * 0.02;
    senses.push(add(x, y, 6.5, "sense", SENSE_LABELS[i]));
  }
  // Process: sampled encoder rows (embed = 64), loose two-column cloud.
  const process = [];
  for (let i = 0; i < ENC_LABELS.length; i++) {
    const col = i % 2;
    const p = Math.floor(i / 2) / 2;
    const x = 0.27 + col * 0.09 + (R() - 0.5) * 0.04;
    const y = lerp(0.22, 0.78, p) + (R() - 0.5) * 0.05;
    process.push(add(x, y, 5.5, "process", ENC_LABELS[i]));
  }
  // MEMORY spine: 12 real GRU units of the representative brain (of
  // DATA.hidden total), true indices as labels, sized by measured activity.
  const memory = [];
  for (let i = 0; i < DATA.display_units.length; i++) {
    const p = i / (DATA.display_units.length - 1);
    const y = lerp(0.10, 0.90, p);
    const x = 0.565 + 0.028 * Math.sin(p * Math.PI * 1.35 + 0.4);
    const r = 8.5 + 4 * DATA.unit_activity[i];
    memory.push(add(x, y, r, "memory", "unit " + DATA.display_units[i]));
    nodes[nodes.length - 1].unit = DATA.display_units[i];
    nodes[nodes.length - 1].signal = DATA.unit_signal[i];
  }
  // Actions: the 5 real motor heads; guesses: the 3 real readout heads.
  const actions = [];
  for (let i = 0; i < ACTION_LABELS.length; i++) {
    const p = i / (ACTION_LABELS.length - 1);
    actions.push(add(0.82 + (R() - 0.5) * 0.02, lerp(0.22, 0.78, p), 6.5, "action", ACTION_LABELS[i]));
  }
  const guesses = [];
  for (let i = 0; i < GUESS_LABELS.length; i++) {
    guesses.push(add(0.945, lerp(0.3, 0.7, i / 2), 6, "guess", GUESS_LABELS[i]));
  }

  // Clue cells: the units with the highest MEASURED world-signal
  // (DATA.ring_units). Ring strength = normalized measured signal; the bloom
  // still cascades top -> bottom along the spine.
  const clue = memory.filter((idx) => DATA.ring_units.includes(nodes[idx].unit));
  nodes.forEach((n, i) => { n.clue = clue.includes(i); });
  clue.forEach((idx, k) => { nodes[idx].clueOrder = k; });
  // The flaw: the sloppy velocity law enters through the motion senses.
  const glitch = senses[GLITCH_SENSE];
  nodes[glitch].glitch = true;

  // Edges. Comets ride a subset; periods divide T for seamless looping.
  const P_CHOICES = [2000, 3000, 4000, 6000];
  const connect = (from, to, fanMin, fanMax, cometProb) => {
    for (const a of from) {
      const fan = fanMin + Math.floor(R() * (fanMax - fanMin + 1));
      for (let k = 0; k < fan; k++) {
        const b = to[Math.floor(R() * to.length)];
        const w = 0.35 + R() * 0.65;
        const comet = R() < cometProb
          ? { P: P_CHOICES[Math.floor(R() * P_CHOICES.length)], phi: R() }
          : null;
        edges.push({ a, b, w, comet });
      }
    }
  };
  connect(senses, process, 2, 3, 0.5);
  connect(process, memory, 2, 3, 0.55);
  connect(memory, actions, 1, 2, 0.45);
  connect(memory.filter((_, i) => i % 3 === 0), guesses, 1, 1, 0.6);

  return { nodes, edges, memory, clue };
}

// Same seed on both sides: it is the SAME brain in two worlds.
const MIND = buildMind(20260811);

// ---------------------------------------------------------------- panels
// Wide: two panels side by side, mirrored. Vertical: stacked.
function panelRects() {
  if (LAYOUT === "vertical") {
    // Stacked panels with room below each for group labels, then narration
    // and caption at the bottom (no overlap: labels sit at y + h + 40).
    const ph = H * 0.33, pw = W * 0.86;
    return [
      { x: (W - pw) / 2, y: H * 0.10, w: pw, h: ph, mirror: false, label: "REAL WORLD" },
      { x: (W - pw) / 2, y: H * 0.50, w: pw, h: ph, mirror: true, label: "FAKE WORLD" },
    ];
  }
  const pw = W * 0.415, ph = H * 0.60;
  const gap = W * 0.055;
  const y = H * 0.115;
  return [
    { x: W / 2 - gap / 2 - pw, y, w: pw, h: ph, mirror: false, label: "REAL WORLD" },
    { x: W / 2 + gap / 2, y, w: pw, h: ph, mirror: true, label: "FAKE WORLD" },
  ];
}
const PANELS = panelRects();

function rawXY(panel, n) {
  const lx = panel.mirror ? 1 - n.x : n.x;
  return [panel.x + lx * panel.w, panel.y + n.y * panel.h];
}

function panelFocusCenter(panel) {
  // Centroid of the focused group in this panel's raw (unzoomed) space.
  if (panel._fc) return panel._fc;
  let sx = 0, sy = 0, k = 0;
  for (const nd of MIND.nodes) {
    if (!SECTION.focus.includes(nd.kind)) continue;
    const [x, y] = rawXY(panel, nd);
    sx += x; sy += y; k++;
  }
  panel._fc = [sx / Math.max(1, k), sy / Math.max(1, k)];
  return panel._fc;
}

function nodeXY(panel, n) {
  const [x, y] = rawXY(panel, n);
  if (FOCUS_Z === 1) return [x, y];
  // Camera: move the focused centroid to the panel center and magnify about
  // it, so the section's subject fills the frame and the rest exits stage.
  const [fx, fy] = panelFocusCenter(panel);
  const cx = panel.x + panel.w / 2;
  const cy = panel.y + panel.h / 2;
  return [cx + (x - fx) * FOCUS_Z, cy + (y - fy) * FOCUS_Z];
}

// ---------------------------------------------------------------- timing
// One "training sweep" per loop crosses each panel; as it passes the memory
// spine the clue rings bloom, hold with a glow-pulse, then decay before the
// next pass. All envelopes are functions of u = (t mod T)/T.

const SWEEP_IN = 0.10, SWEEP_OUT = 0.46;   // sweep front active window (u)
const BLOOM_AT = 0.30;                      // u when front hits the spine
const BLOOM_STAGGER = 0.022;                // per-cell delay (u units)
const RING_HOLD_END = 0.86;                 // u when rings start to release
const RING_DECAY = 0.10;                    // release length (u units)

function sweepX(panel, u) {
  // Front sweeps across the panel from the senses side toward actions.
  const s = smooth((u - SWEEP_IN) / (SWEEP_OUT - SWEEP_IN));
  const x0 = panel.mirror ? panel.x + panel.w * 1.08 : panel.x - panel.w * 0.08;
  const x1 = panel.mirror ? panel.x - panel.w * 0.08 : panel.x + panel.w * 1.08;
  return lerp(x0, x1, s);
}
function sweepAlpha(u) {
  const a = smooth((u - SWEEP_IN) / 0.05) * (1 - smooth((u - SWEEP_OUT + 0.05) / 0.05));
  return 0.85 * a;
}

function ringEnv(u, order) {
  const start = BLOOM_AT + order * BLOOM_STAGGER;
  const uu = frac(u - start + 1);           // time since this cell's bloom, in u
  const attack = smooth(uu / 0.03);          // ~0.36s bloom-in
  const releaseAt = frac(RING_HOLD_END - start + 1);
  const rel = 1 - smooth((uu - releaseAt) / RING_DECAY);
  return clamp01(attack * rel);
}

// ---------------------------------------------------------------- canvas
const canvas = document.getElementById("stage");
canvas.width = W; canvas.height = H;
const ctx = canvas.getContext("2d");

function bezier(ax, ay, bx, by, s) {
  // Quadratic with a control point pushed perpendicular for a gentle arc.
  const mx = (ax + bx) / 2, my = (ay + by) / 2;
  const dx = bx - ax, dy = by - ay;
  const L = Math.hypot(dx, dy) || 1;
  const cx = mx - dy / L * L * 0.14, cy = my + dx / L * L * 0.14;
  const q = 1 - s;
  return [
    q * q * ax + 2 * q * s * cx + s * s * bx,
    q * q * ay + 2 * q * s * cy + s * s * by,
    cx, cy,
  ];
}

function drawBackground(t) {
  const u = frac(t / T);
  ctx.fillStyle = BG0;
  ctx.fillRect(0, 0, W, H);
  // Slow nebula blobs on closed Lissajous paths (integer cycles => seamless).
  const blobs = [
    { cx: 0.24, cy: 0.30, r: 0.55, c: [34, 28, 66], k1: 1, k2: 2, amp: 0.045, phi: 0.0 },
    { cx: 0.78, cy: 0.34, r: 0.50, c: [46, 26, 62], k1: 1, k2: 1, amp: 0.05, phi: 2.1 },
    { cx: 0.52, cy: 0.78, r: 0.62, c: [24, 30, 58], k1: 2, k2: 1, amp: 0.04, phi: 4.0 },
  ];
  for (const b of blobs) {
    const x = (b.cx + b.amp * Math.cos(TAU * b.k1 * u + b.phi)) * W;
    const y = (b.cy + b.amp * Math.sin(TAU * b.k2 * u + b.phi)) * H;
    const r = b.r * Math.max(W, H);
    const g = ctx.createRadialGradient(x, y, 0, x, y, r);
    g.addColorStop(0, rgba(b.c, 0.55));
    g.addColorStop(1, rgba(b.c, 0));
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, W, H);
  }
}

function nodeColor(panel, n) {
  if (n.kind === "guess") return AMBER;
  if (n.glitch && panel.mirror) return CORAL;
  return panel.mirror ? FAKE_C : REAL_C;
}

function drawScanlines(panel, t) {
  // Faint drifting scanlines: the fake world is a rendered world.
  const u = frac(t / T);
  const off = (u * 14) % 7; // one 7px cell of drift per loop => seamless
  ctx.save();
  ctx.beginPath();
  ctx.rect(panel.x - 40, panel.y - 20, panel.w + 80, panel.h + 40);
  ctx.clip();
  ctx.strokeStyle = "rgba(169,139,224,0.035)";
  ctx.lineWidth = 1;
  for (let y = panel.y - 20 + off; y < panel.y + panel.h + 40; y += 7) {
    ctx.beginPath();
    ctx.moveTo(panel.x - 40, y);
    ctx.lineTo(panel.x + panel.w + 40, y);
    ctx.stroke();
  }
  ctx.restore();
}

function drawMind(panel, t) {
  const u = frac(t / T);
  const fx = sweepX(panel, u), fa = sweepAlpha(u);

  // FAKE side: the world itself is rendered - faint scanlines carry the tell.
  // (An earlier panel-wide "digital shudder" was cut: it read as a rendering
  // glitch rather than a story beat.)
  ctx.save();
  // Panel clip: under the focus camera, pushed-out nodes must not spill into
  // the neighboring panel or the caption band.
  ctx.beginPath();
  if (LAYOUT === "vertical") {
    ctx.rect(0, panel.y - 110, W, panel.h + 170);
  } else if (panel.mirror) {
    ctx.rect(W / 2 + 6, panel.y - 110, panel.x + panel.w + 160 - (W / 2 + 6), panel.h + 170);
  } else {
    ctx.rect(panel.x - 160, panel.y - 110, W / 2 - 6 - (panel.x - 160), panel.h + 170);
  }
  ctx.clip();
  if (panel.mirror) {
    drawScanlines(panel, t);
  }

  // --- edges (filaments)
  ctx.lineCap = "round";
  for (const e of MIND.edges) {
    const A = MIND.nodes[e.a], B = MIND.nodes[e.b];
    const [ax, ay] = nodeXY(panel, A);
    const [bx, by] = nodeXY(panel, B);
    const [, , cx, cy] = bezier(ax, ay, bx, by, 0.5);
    const base = panel.mirror ? FAKE_C : REAL_C;
    const em = Math.max(kindEmphasis(A.kind), kindEmphasis(B.kind));
    ctx.strokeStyle = rgba(base, (0.05 + 0.1 * e.w) * em);
    ctx.lineWidth = (0.8 + e.w * 1.4) * FOCUS_Z;
    ctx.beginPath();
    ctx.moveTo(ax, ay);
    ctx.quadraticCurveTo(cx, cy, bx, by);
    ctx.stroke();
  }

  // --- comets (signal pulses riding filaments)
  for (const e of MIND.edges) {
    if (!e.comet) continue;
    const A = MIND.nodes[e.a], B = MIND.nodes[e.b];
    const [ax, ay] = nodeXY(panel, A);
    const [bx, by] = nodeXY(panel, B);
    const s = frac(t / e.comet.P + e.comet.phi + (panel.mirror ? 0.5 : 0));
    const [px, py] = bezier(ax, ay, bx, by, s);
    // The flaw propagates: signals leaving the glitched sense carry its tint.
    const base = A.glitch && panel.mirror
      ? CORAL
      : panel.mirror ? FAKE_C : REAL_C;
    const bright = [
      Math.min(255, base[0] + 70),
      Math.min(255, base[1] + 70),
      Math.min(255, base[2] + 60),
    ];
    const cem = Math.max(kindEmphasis(A.kind), kindEmphasis(B.kind));
    // Tail: a few ghost dots behind the head.
    for (let k = 3; k >= 1; k--) {
      const [tx, ty] = bezier(ax, ay, bx, by, Math.max(0, s - k * 0.03));
      ctx.fillStyle = rgba(base, 0.10 * (4 - k) * e.w * cem);
      ctx.beginPath(); ctx.arc(tx, ty, 2.2 * FOCUS_Z, 0, TAU); ctx.fill();
    }
    const cr = 9 * FOCUS_Z;
    const g = ctx.createRadialGradient(px, py, 0, px, py, cr);
    g.addColorStop(0, rgba(bright, 0.9 * e.w * cem));
    g.addColorStop(1, rgba(bright, 0));
    ctx.fillStyle = g;
    ctx.beginPath(); ctx.arc(px, py, cr, 0, TAU); ctx.fill();
  }

  // --- training sweep front (soft luminous band + thin leading crest)
  if (fa > 0.01) {
    const bw = panel.w * 0.16;
    const g = ctx.createLinearGradient(fx - bw, 0, fx + bw, 0);
    g.addColorStop(0, rgba(TEAL, 0));
    g.addColorStop(0.5, rgba(TEAL, 0.055 * fa));
    g.addColorStop(1, rgba(TEAL, 0));
    ctx.fillStyle = g;
    ctx.fillRect(fx - bw, panel.y - 30, bw * 2, panel.h + 60);
    const crest = ctx.createLinearGradient(fx - 3, 0, fx + 3, 0);
    crest.addColorStop(0, rgba(TEAL, 0));
    crest.addColorStop(0.5, rgba(TEAL, 0.16 * fa));
    crest.addColorStop(1, rgba(TEAL, 0));
    ctx.fillStyle = crest;
    ctx.fillRect(fx - 3, panel.y - 30, 6, panel.h + 60);
  }

  // --- nodes
  for (const n of MIND.nodes) {
    const [x, y] = nodeXY(panel, n);
    const breathe = 1 + 0.09 * Math.sin(TAU * n.freqK * (t / T) + n.phase);
    // Sweep boost: nodes glow as the front passes them.
    const boost = fa * Math.exp(-Math.pow((x - fx) / (panel.w * 0.07), 2));
    const base = nodeColor(panel, n);
    // The flaw node stays vivid in every section; other nodes follow focus.
    const em = n.glitch && panel.mirror ? 1 : kindEmphasis(n.kind);
    const r = n.r * FOCUS_Z * breathe * (1 + 0.35 * boost);
    const glowR = r * (n.kind === "memory" ? 3.4 : 2.6);
    const g = ctx.createRadialGradient(x, y, 0, x, y, glowR);
    g.addColorStop(0, rgba(base, (0.30 + 0.35 * boost) * em));
    g.addColorStop(1, rgba(base, 0));
    ctx.fillStyle = g;
    ctx.beginPath(); ctx.arc(x, y, glowR, 0, TAU); ctx.fill();
    ctx.fillStyle = rgba(base, 0.95 * em);
    ctx.beginPath(); ctx.arc(x, y, r, 0, TAU); ctx.fill();
    ctx.fillStyle = `rgba(255,255,255,${0.55 * em})`;
    ctx.beginPath(); ctx.arc(x - r * 0.25, y - r * 0.28, r * 0.32, 0, TAU); ctx.fill();
  }

  // --- teal clue rings on memory cells (the story). When another group is
  // the camera subject, the rings dim with the rest of memory so they read
  // as background context, not competition.
  const memEm = kindEmphasis("memory");
  for (const idx of MIND.clue) {
    const n = MIND.nodes[idx];
    const [x, y] = nodeXY(panel, n);
    const env = ringEnv(u, n.clueOrder) * memEm;
    if (env <= 0.01) continue;
    const pulse = 1 + 0.06 * Math.sin(TAU * 3 * (t / T) + n.clueOrder * 1.1);
    const rr = (n.r + 7.5) * FOCUS_Z * pulse;

    // Bloom ripple right after this cell's ring is born.
    const start = BLOOM_AT + n.clueOrder * BLOOM_STAGGER;
    const since = frac(u - start + 1);
    if (since < 0.05) {
      const rp = since / 0.05;
      ctx.strokeStyle = rgba(TEAL, 0.5 * (1 - rp) * memEm);
      ctx.lineWidth = 2;
      ctx.beginPath(); ctx.arc(x, y, rr + rp * 34, 0, TAU); ctx.stroke();
    }

    // Ring intensity follows the MEASURED per-unit world-signal.
    const st = n.signal || 1;
    const g = ctx.createRadialGradient(x, y, rr * 0.4, x, y, rr * 2.6);
    g.addColorStop(0, rgba(TEAL, 0));
    g.addColorStop(0.45, rgba(TEAL, 0.22 * env * st));
    g.addColorStop(1, rgba(TEAL, 0));
    ctx.fillStyle = g;
    ctx.beginPath(); ctx.arc(x, y, rr * 2.6, 0, TAU); ctx.fill();

    ctx.strokeStyle = rgba(TEAL, 0.95 * env * st);
    ctx.lineWidth = 3;
    ctx.beginPath(); ctx.arc(x, y, rr, 0, TAU); ctx.stroke();
    ctx.strokeStyle = rgba(TEAL, 0.35 * env * st);
    ctx.lineWidth = 1.5;
    ctx.beginPath(); ctx.arc(x, y, rr + 5, 0, TAU); ctx.stroke();
  }

  // --- the flaw: flicker + warning ripple on the glitched sense, both panels
  //     get a physics label so the ONE difference between worlds is explicit.
  //     Under the focus camera this only appears when senses are the subject
  //     (otherwise the flaw node is out of frame and the label would dangle).
  if (FOCUS_Z === 1 || SECTION.focus.includes("sense")) {
    const gn = MIND.nodes.find((n) => n.glitch);
    const [gx, gy] = nodeXY(panel, gn);
    const dir = panel.mirror ? 1 : -1;
    if (panel.mirror) {
      // Fast periodic flicker (integer cycles => seamless) + dashed alarm ring.
      const fl = 0.5 + 0.5 * Math.abs(Math.sin(TAU * 9 * u + 1.7) * Math.sin(TAU * 4 * u));
      ctx.setLineDash([4, 4]);
      ctx.strokeStyle = rgba(CORAL, 0.35 + 0.5 * fl);
      ctx.lineWidth = 2;
      ctx.beginPath(); ctx.arc(gx, gy, (gn.r + 8) * FOCUS_Z, 0, TAU); ctx.stroke();
      ctx.setLineDash([]);
      // Quarter-loop warning ripples.
      const q = frac(u * 4);
      if (q < 0.35) {
        const p = q / 0.35;
        ctx.strokeStyle = rgba(CORAL, 0.4 * (1 - p));
        ctx.lineWidth = 1.5;
        ctx.beginPath(); ctx.arc(gx, gy, (gn.r + 6) * FOCUS_Z + p * 30, 0, TAU); ctx.stroke();
      }
    }
    // Physics label with underline leader, pointing toward the outer edge but
    // clamped inside a canvas-safe margin.
    const label = panel.mirror ? "sloppy physics" : "true physics";
    const col = panel.mirror ? CORAL : REAL_C;
    const ly = gy - 46;
    const endX = panel.mirror
      ? Math.min(gx + 182, W - 22)
      : Math.max(gx - 182, 22);
    ctx.strokeStyle = rgba(col, 0.45);
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(gx + dir * 16, gy - 12);
    ctx.lineTo(gx + dir * 44, ly);
    ctx.lineTo(endX, ly);
    ctx.stroke();
    ctx.font = "600 25px 'Segoe UI', sans-serif";
    ctx.textAlign = panel.mirror ? "right" : "left";
    ctx.textBaseline = "alphabetic";
    textShadowOn();
    ctx.fillStyle = rgba(col, 0.95);
    ctx.fillText(label, endX, ly - 8);
    textShadowOff();
  }

  // --- per-dot labels (real channel / unit / head names)
  drawNodeLabels(panel, u);

  // --- stage labels under each functional group, with flow chevrons
  drawGroupLabels(panel, u);

  // --- verdict meter: same brain, different answer
  drawVerdict(panel, u);

  // (The old "clue cell" callout is gone: the ringed cells now carry their
  // real unit labels, and the caption already translates what a ring means.)

  // --- panel label
  ctx.font = "600 34px 'Segoe UI', sans-serif";
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  ctx.fillStyle = rgba(TEAL, 0.95);
  const lw = ctx.measureText(panel.label).width;
  ctx.save();
  ctx.letterSpacing = "6px";
  textShadowOn();
  ctx.fillText(panel.label, panel.x + panel.w / 2, panel.y - 42);
  textShadowOff();
  ctx.restore();
  ctx.strokeStyle = rgba(TEAL, 0.35);
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(panel.x + panel.w / 2 - lw / 2 - 26, panel.y - 42);
  ctx.lineTo(panel.x + panel.w / 2 - lw / 2 - 56, panel.y - 42);
  ctx.moveTo(panel.x + panel.w / 2 + lw / 2 + 26, panel.y - 42);
  ctx.lineTo(panel.x + panel.w / 2 + lw / 2 + 56, panel.y - 42);
  ctx.stroke();

  ctx.restore(); // close jitter/scanline wrapper
}

// REAL canonical numbers (docs/FINDINGS.md TL;DR, L3, n = 10 seeds):
// untrained floor, pre-registered "can tell" bar, survival-trained result.
const AUROC_UNTRAINED = 0.488;
const AUROC_TRAINED = 0.752;
const AUROC_BAR = 0.65;

// Verdict meter under each panel title: both minds start at the measured
// untrained floor (~chance), then resolve to DIFFERENT answers as the rings
// bloom - same brain, two conclusions - rising past the pre-registered 0.65
// bar to the measured 0.752, and falling back when the clue fades
// (loop-periodic). Track spans 50% (chance) to 100%.
function drawVerdict(panel, u) {
  let env = 0;
  for (let k = 0; k < 6; k++) env += ringEnv(u, k);
  env /= 6;
  const v = lerp(AUROC_UNTRAINED, AUROC_TRAINED, env);
  const fill = clamp01((v - 0.5) / 0.5);
  const cx = panel.x + panel.w / 2;
  const tw = 250, ty = panel.y - 8;
  const x0 = cx - tw / 2;

  ctx.strokeStyle = "rgba(96,86,150,0.4)";
  ctx.lineWidth = 2;
  ctx.beginPath(); ctx.moveTo(x0, ty); ctx.lineTo(x0 + tw, ty); ctx.stroke();
  // Chance tick at the left end of the scale.
  ctx.strokeStyle = "rgba(120,114,143,0.6)";
  ctx.beginPath(); ctx.moveTo(x0, ty - 5); ctx.lineTo(x0, ty + 5); ctx.stroke();
  ctx.font = "400 17px 'Segoe UI', sans-serif";
  ctx.textAlign = "left"; ctx.textBaseline = "middle";
  textShadowOn();
  ctx.fillStyle = "rgba(150,145,175,0.85)";
  ctx.fillText("50% = chance", x0 + 6, ty - 12);
  textShadowOff();
  // Pre-registered pass bar at 0.65: "past this line = it can tell".
  const bx = x0 + tw * clamp01((AUROC_BAR - 0.5) / 0.5);
  ctx.strokeStyle = rgba(TEAL, 0.55);
  ctx.beginPath(); ctx.moveTo(bx, ty - 6); ctx.lineTo(bx, ty + 6); ctx.stroke();

  ctx.strokeStyle = rgba(TEAL, 0.35 + 0.55 * env);
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(x0, ty);
  ctx.lineTo(x0 + tw * fill, ty);
  ctx.stroke();

  ctx.font = "600 24px 'Segoe UI', sans-serif";
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  textShadowOn();
  const know = smooth((env - 0.12) / 0.18);
  const pct = Math.round(v * 100);
  if (know < 1) {
    ctx.fillStyle = `rgba(150,145,175,${0.9 * (1 - know)})`;
    ctx.fillText(`can't tell yet · ${pct}%`, cx, ty + 22);
  }
  if (know > 0) {
    ctx.fillStyle = rgba(TEAL, 0.95 * know);
    ctx.fillText(
      `reads ${panel.mirror ? "FAKE" : "REAL"} · ${pct}%`,
      cx, ty + 22,
    );
  }
  textShadowOff();
}

// Per-dot labels with the real names. Shown where there is room to read them:
// each zoomed section labels its subject dots; the memory section labels the
// ringed clue cells, fading in with their rings. Overview stays clean.
function drawNodeLabels(panel, u) {
  const zoomed = FOCUS_Z > 1;
  const memorySec = !zoomed && SEC === "memory";
  if (!zoomed && !memorySec) return;
  ctx.textBaseline = "middle";
  textShadowOn();
  for (const n of MIND.nodes) {
    if (!n.label) continue;
    let alpha;
    if (zoomed) {
      if (!SECTION.focus.includes(n.kind)) continue;
      alpha = 0.9;
      ctx.font = "600 21px 'Segoe UI', sans-serif";
    } else {
      if (!n.clue) continue;
      const env = ringEnv(u, n.clueOrder);
      if (env < 0.15) continue;
      alpha = 0.85 * smooth((env - 0.15) / 0.3);
      ctx.font = "600 19px 'Segoe UI', sans-serif";
    }
    // Side: away from crowded neighbors. Actions point into the panel; all
    // other groups label toward the panel's inner space. Mirroring flips.
    let side = n.kind === "action" ? -1 : 1;
    if (panel.mirror) side = -side;
    const [x, y] = nodeXY(panel, n);
    const off = n.r * FOCUS_Z + 14;
    ctx.textAlign = side > 0 ? "left" : "right";
    ctx.fillStyle = memorySec
      ? rgba(TEAL, alpha)
      : `rgba(214,209,232,${alpha})`;
    ctx.fillText(n.label, x + side * off, y);
  }
  textShadowOff();
}

// Group label positions: centroid x of each kind, on a baseline under the panel.
function groupCentroidX(panel, kind) {
  let sx = 0, n = 0;
  for (const nd of MIND.nodes) {
    if (nd.kind !== kind) continue;
    sx += nodeXY(panel, nd)[0]; n++;
  }
  return sx / Math.max(1, n);
}

function drawGroupLabels(panel, u) {
  const y = panel.y + panel.h + 40;
  if (FOCUS_Z > 1) {
    // Under the focus camera the other groups are out of frame; a single
    // centered label names the subject and nothing else.
    const name = SECTION.focus.includes("sense")
      ? "SENSES"
      : SECTION.focus.includes("process")
        ? "PROCESS"
        : "ACTIONS · GUESSES";
    ctx.save();
    ctx.letterSpacing = "3px";
    ctx.textAlign = "center"; ctx.textBaseline = "middle";
    ctx.font = "700 27px 'Segoe UI', sans-serif";
    textShadowOn();
    ctx.fillStyle = rgba(TEAL, 0.95);
    ctx.fillText(name, panel.x + panel.w / 2, y);
    textShadowOff();
    ctx.restore();
    return;
  }
  // Actions + guesses sit close together; one merged label avoids a collision.
  const labels = [
    { x: groupCentroidX(panel, "sense"), text: "SENSES", kinds: ["sense"] },
    { x: groupCentroidX(panel, "process"), text: "PROCESS", kinds: ["process"] },
    { x: groupCentroidX(panel, "memory"), text: "MEMORY", kinds: ["memory"] },
    {
      x: (groupCentroidX(panel, "action") + groupCentroidX(panel, "guess")) / 2,
      text: "ACTIONS · GUESSES",
      kinds: ["action", "guess"],
    },
  ];
  const xs = labels.map((l) => l.x);
  // MEMORY label glows teal while any ring is up; the section's focused
  // group also reads brighter than the supporting cast.
  const memGlow = ringEnv(u, 0);

  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  ctx.save();
  ctx.letterSpacing = "3px";
  textShadowOn();
  labels.forEach((l) => {
    // Clamp under the focus camera so labels stay within their panel.
    const lx = Math.max(panel.x + 70, Math.min(panel.x + panel.w - 70, l.x));
    const focused = SECTION.focus && l.kinds.some((k) => SECTION.focus.includes(k));
    const hot = l.kinds[0] === "memory" && memGlow > 0.1;
    ctx.font = focused
      ? "700 26px 'Segoe UI', sans-serif"
      : "600 23px 'Segoe UI', sans-serif";
    ctx.fillStyle = hot
      ? rgba(TEAL, 0.65 + 0.35 * memGlow)
      : focused
        ? rgba(TEAL, 0.95)
        : "rgba(150,145,175,0.85)";
    ctx.fillText(l.text, lx, y);
  });
  textShadowOff();
  ctx.restore();

  // Flow chevrons between adjacent labels, pointing senses -> guesses.
  ctx.font = "600 20px 'Segoe UI', sans-serif";
  ctx.fillStyle = "rgba(150,145,175,0.6)";
  for (let i = 0; i < xs.length - 1; i++) {
    const mx = (xs[i] + xs[i + 1]) / 2;
    ctx.fillText(xs[i + 1] > xs[i] ? "›" : "‹", mx, y - 1);
  }
}

// ------------------------------------------------------------- text layout
// Canvas has no wrapping: measure-and-wrap, then balance so multi-line blocks
// come out with near-equal line lengths instead of a long line + an orphan.
function wrapLines(text, maxWidth) {
  const words = text.split(" ");
  const lines = [];
  let cur = "";
  for (const w of words) {
    const trial = cur ? cur + " " + w : w;
    if (cur && ctx.measureText(trial).width > maxWidth) { lines.push(cur); cur = w; }
    else cur = trial;
  }
  if (cur) lines.push(cur);
  return lines;
}
function balancedLines(text, maxWidth) {
  const greedy = wrapLines(text, maxWidth);
  if (greedy.length < 2) return greedy;
  const n = greedy.length;
  let lo = ctx.measureText(text).width / n, hi = maxWidth;
  for (let i = 0; i < 8; i++) {
    const mid = (lo + hi) / 2;
    if (wrapLines(text, mid).length > n) lo = mid; else hi = mid;
  }
  return wrapLines(text, hi);
}
// Vertically-centered multi-line block at (W/2, yc).
function fillBlock(lines, yc, lineH) {
  const y0 = yc - ((lines.length - 1) * lineH) / 2;
  lines.forEach((l, i) => ctx.fillText(l, W / 2, y0 + i * lineH));
}

// Bottom text band metrics per layout: narration block, headline, sub-line.
// Absolute pixels (W/H are constants) chosen so nothing collides with the
// panel group labels above or the canvas edge below, with safe side margins.
const TXT = LAYOUT === "vertical"
  ? { narrY: 1706, narrSize: 34, narrLH: 44, narrMax: 940,
      headY: 1802, headSize: 48,
      subY: 1858, subSize: 22, subLH: 30, subMax: 940, bandTop: 1590 }
  : { narrY: 884, narrSize: 32, narrLH: 42, narrMax: 1520,
      headY: 956, headSize: 50,
      subY: 1008, subSize: 24, subLH: 30, subMax: 1700, bandTop: 826 };

// Live narration: the story phase-by-phase. Phase windows tile [0,1) in u,
// so the text cycle is loop-periodic like the motion.
function drawNarration(t) {
  const u = frac(t / T);
  const NARRATION = SECTION.narration;
  ctx.font = `500 ${TXT.narrSize}px 'Segoe UI', sans-serif`;
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  textShadowOn();
  for (const ph of NARRATION) {
    const span = ph.u1 - ph.u0;
    const local = (u - ph.u0) / span;
    if (local < 0 || local >= 1) continue;
    const a = smooth(local / 0.12) * (1 - smooth((local - 0.88) / 0.12));
    ctx.fillStyle = `rgba(230,226,244,${0.97 * a})`;
    fillBlock(balancedLines(ph.text, TXT.narrMax), TXT.narrY, TXT.narrLH);
  }
  textShadowOff();
}

function drawDivider(t) {
  if (LAYOUT === "vertical") return;
  const u = frac(t / T);
  const x = W / 2;
  const shimmer = 0.25 + 0.12 * Math.sin(TAU * 2 * u);
  const g = ctx.createLinearGradient(0, H * 0.16, 0, H * 0.72);
  g.addColorStop(0, "rgba(66,58,110,0)");
  g.addColorStop(0.5, `rgba(96,86,150,${shimmer})`);
  g.addColorStop(1, "rgba(66,58,110,0)");
  ctx.strokeStyle = g;
  ctx.lineWidth = 2;
  ctx.beginPath(); ctx.moveTo(x, H * 0.16); ctx.lineTo(x, H * 0.72); ctx.stroke();
}

// Shade band drawn BEFORE the narration so type never gets painted over.
function drawCaptionBand() {
  const g = ctx.createLinearGradient(0, TXT.bandTop, 0, H);
  g.addColorStop(0, "rgba(10,9,16,0)");
  g.addColorStop(0.45, "rgba(10,9,16,0.88)");
  ctx.fillStyle = g;
  ctx.fillRect(0, TXT.bandTop, W, H - TXT.bandTop);
}

function drawCaption() {
  ctx.textAlign = "center"; ctx.textBaseline = "middle";
  textShadowOn();
  ctx.font = `700 ${TXT.headSize}px 'Segoe UI', sans-serif`;
  ctx.fillStyle = INK;
  fillBlock(balancedLines(SECTION.headline, TXT.subMax), TXT.headY, TXT.headSize * 1.15);
  ctx.font = `400 ${TXT.subSize}px 'Segoe UI', sans-serif`;
  ctx.fillStyle = "rgba(168,162,192,0.95)";
  const sub = balancedLines(
    "ItaSoRL  ·  real numbers: memory-probe AUROC, n = 10 seeds  ·  past the 0.65 bar = it can tell",
    TXT.subMax,
  );
  const y0 = TXT.subY;
  sub.forEach((l, i) => ctx.fillText(l, W / 2, y0 + i * TXT.subLH));
  textShadowOff();
}

function drawVignette() {
  const g = ctx.createRadialGradient(W / 2, H / 2, Math.min(W, H) * 0.35, W / 2, H / 2, Math.max(W, H) * 0.75);
  g.addColorStop(0, "rgba(0,0,0,0)");
  g.addColorStop(1, "rgba(0,0,0,0.5)");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, W, H);
}

// ---------------------------------------------------------------- frame
function render(t) {
  t = ((t % T) + T) % T;
  ctx.save();
  // Gentle breathing camera (one full cycle per loop => seamless).
  const s = 1 + 0.012 * Math.sin(TAU * (t / T));
  ctx.translate(W / 2, H / 2); ctx.scale(s, s); ctx.translate(-W / 2, -H / 2);
  drawBackground(t);
  for (const p of PANELS) drawMind(p, t);
  drawDivider(t);
  ctx.restore();
  drawVignette();
  drawCaptionBand();
  drawNarration(t);
  drawCaption();
}

// ---------------------------------------------------------------- boot
window.__size = [W, H];
window.__duration = T;
window.__sceneSource = "stylized";
let rafId = null;
window.__seek = (t) => {
  if (rafId !== null) { cancelAnimationFrame(rafId); rafId = null; }
  render(t);
};

// Live preview when opened in a normal browser (capture calls __seek instead).
function live(ts) {
  render(ts);
  rafId = requestAnimationFrame(live);
}

(document.fonts ? document.fonts.ready : Promise.resolve()).then(() => {
  render(0);
  window.__ready = true;
  rafId = requestAnimationFrame(live);
});
